apiVersion: v1
kind: ConfigMap
metadata:
  name: storage-configmap
  service: storage
data:
  PORT: "{{ .Values.storageConfig.PORT }}"
  STORAGE_ACCOUNT_NAME: "{{ .Values.storageConfig.STORAGE_ACCOUNT_NAME }}"
