replicas: 3
resources:
  requests:
    memory: 1Gi
    cpu: 1
  limits:
    memory: 2Gi
    cpu: 2
volumeClaimTemplate:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 50Gi
