apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.db.service.name }}
  labels:
    app: {{ .Values.db.labels.app }}
    environment: {{ .Values.db.labels.environment }}

spec:
  replicas: {{ .Values.db.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.db.labels.app }}
      service: {{ .Values.db.labels.service }}

  template:
    metadata:
      labels:
        app: {{ .Values.db.labels.app }}
        service: {{ .Values.db.labels.service }}

    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: {{ .Values.db.labels.service }}
          image: "{{ .Values.db.image.repository }}:{{ .Values.db.image.tag }}"
          imagePullPolicy: {{ .Values.db.image.pullPolicy }}

          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "mytube"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "secretpassword"
            - name: MONGO_INITDB_DATABASE
              value: "mydb"

          ports:
            - containerPort: {{ .Values.db.service.port }}
