apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.storage.service.name }}
  labels:
    app: {{ .Values.storage.labels.app }}
    environment: {{ .Values.storage.labels.environment }}

spec:
  replicas: {{ .Values.storage.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.storage.labels.app }}
      service: {{ .Values.storage.labels.service }}
      provider: {{ .Values.storage.labels.provider }}

  template:
    metadata:
      labels:
        app: {{ .Values.storage.labels.app }}
        service: {{ .Values.storage.labels.service }}
        provider: {{ .Values.storage.labels.provider }}

    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: {{ .Values.storage.image.tag }}
          image: "{{ .Values.storage.image.repository }}:{{ .Values.storage.image.tag }}"
          imagePullPolicy: {{ .Values.storage.image.pullPolicy }}
          
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: storage-configmap
                  key: PORT
            - name: STORAGE_ACCOUNT_NAME
              valueFrom:
                configMapKeyRef:
                  name: storage-configmap
                  key: STORAGE_ACCOUNT_NAME
            - name: STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: azure-storage-access-key
                  key: STORAGE_ACCESS_KEY
          
          resources:
            limits:
              memory: {{ .Values.storage.resources.limits.memory }}
              cpu: {{ .Values.storage.resources.limits.cpu }}
          ports:
            - containerPort: {{ .Values.storage.service.port }}
