apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbIP.name }}
  labels:
    app: {{ .Values.dbIP.labels.app }}
    environment: {{ .Values.dbIP.labels.environment }}
spec:
  type: {{ .Values.dbIP.type }}
  selector:
    app: {{ .Values.dbIP.labels.app }}
    service: {{ .Values.dbIP.labels.service }}
  ports:
    - protocol: TCP
      port: {{ .Values.dbIP.port }}
      targetPort: {{ .Values.dbIP.targetPort }}
