apiVersion: v1
kind: ConfigMap
metadata:
  name: mytube
  service: storage
data:
  PORT: { { .Values.streamingConfig.PORT } }
  STORAGE_ACCOUNT_NAME: { { .Values.streamingConfig.STORAGE_ACCOUNT_NAME } }
