apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.streamingIP.name }}
  labels:
    app: {{ .Values.streamingIP.labels.app }}
    environment: {{ .Values.streaming.labels.environment }}
spec:
  type: {{ .Values.streamingIP.type }}
  selector:
    app: {{ .Values.streamingIP.labels.app }}
    service: {{ .Values.streamingIP.labels.service }}
  ports:
  - protocol: TCP
    port: {{ .Values.streamingIP.port }}
    targetPort: {{ .Values.streamingIP.targetPort }}
