apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: Prometheus
  metadata:
    annotations:
      meta.helm.sh/release-name: stable
      meta.helm.sh/release-namespace: prometheus
    creationTimestamp: "2024-09-30T11:49:19Z"
    generation: 1
    labels:
      app: kube-prometheus-stack-prometheus
      app.kubernetes.io/instance: stable
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/part-of: kube-prometheus-stack
      app.kubernetes.io/version: 63.1.0
      chart: kube-prometheus-stack-63.1.0
      heritage: Helm
      release: stable
    name: stable-kube-prometheus-sta-prometheus
    namespace: prometheus
    resourceVersion: "11502"
    uid: 800876d1-98f3-4457-a985-eac23a50c92b
  spec:
    alerting:
      alertmanagers:
      - apiVersion: v2
        name: stable-kube-prometheus-sta-alertmanager
        namespace: prometheus
        pathPrefix: /
        port: http-web
    automountServiceAccountToken: true
    enableAdminAPI: false
    evaluationInterval: 30s
    externalUrl: http://stable-kube-prometheus-sta-prometheus.prometheus:9090
    hostNetwork: false
    image: quay.io/prometheus/prometheus:v2.54.1
    listenLocal: false
    logFormat: logfmt
    logLevel: info
    paused: false
    podMonitorNamespaceSelector: {}
    podMonitorSelector:
      matchLabels:
        release: stable
    portName: http-web
    probeNamespaceSelector: {}
    probeSelector:
      matchLabels:
        release: stable
    replicas: 1
    retention: 10d
    routePrefix: /
    ruleNamespaceSelector: {}
    ruleSelector:
      matchLabels:
        release: stable
    scrapeConfigNamespaceSelector: {}
    scrapeConfigSelector:
      matchLabels:
        release: stable
    scrapeInterval: 30s
    securityContext:
      fsGroup: 2000
      runAsGroup: 2000
      runAsNonRoot: true
      runAsUser: 1000
      seccompProfile:
        type: RuntimeDefault
    serviceAccountName: stable-kube-prometheus-sta-prometheus
    serviceMonitorNamespaceSelector: {}
    serviceMonitorSelector:
      matchLabels:
        release: stable
    shards: 1
    tsdb:
      outOfOrderTimeWindow: 0s
    version: v2.54.1
    walCompression: true
  status:
    availableReplicas: 1
    conditions:
    - lastTransitionTime: "2024-10-05T08:20:34Z"
      message: ""
      observedGeneration: 1
      reason: ""
      status: "True"
      type: Available
    - lastTransitionTime: "2024-10-05T08:20:34Z"
      message: ""
      observedGeneration: 1
      reason: ""
      status: "True"
      type: Reconciled
    paused: false
    replicas: 1
    selector: app.kubernetes.io/instance=stable-kube-prometheus-sta-prometheus,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,operator.prometheus.io/name=stable-kube-prometheus-sta-prometheus,prometheus=stable-kube-prometheus-sta-prometheus
    shardStatuses:
    - availableReplicas: 1
      replicas: 1
      shardID: "0"
      unavailableReplicas: 0
      updatedReplicas: 1
    shards: 1
    unavailableReplicas: 0
    updatedReplicas: 1
kind: List
metadata:
  resourceVersion: ""
