apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mongodb-exporter-monitor
  namespace: default
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: prometheus-mongodb-exporter
  endpoints:
    - port: metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - monitoring
