#### STREAMING SERVICE ######
# Streaming Deployment Object
streaming:
  replicaCount: 1

  image:
    repository: mhs20/mytube
    tag: video-streaming-010
    pullPolicy: IfNotPresent

  resources:
    limits:
      memory: "128Mi"
      cpu: "500m"

  service:
    name: video-streaming
    port: 4002

  labels:
    app: mytube
    environment: dev
    service: streaming

# Streaming ClusterIP Service
streamingIP:
  name: video-streaming
  type: ClusterIP
  port: 4002
  targetPort: 4002
  labels:
    app: mytube
    service: streaming

# Streaming ConfigMap
streamingConfig:
  PORT: 4002
  VIDEO_STORAGE_HOST: azure-storage
  VIDEO_STORAGE_PORT: 4001
  DBHOST: mongodb://mytube:secretpassword@mytube-db:4000/
  # DBHOST: mytube-db
  DBNAME: mydb

#### STORAGE SERVICE ######
# Storage Deployment Object
storage:
  replicaCount: 1

  image:
    repository: mhs20/mytube
    tag: azure-storage-010
    pullPolicy: IfNotPresent

  resources:
    limits:
      memory: "128Mi"
      cpu: "500m"

  service:
    name: azure-storage
    port: 4001

  labels:
    app: mytube
    environment: dev
    service: storage
    provider: azure

# Storage ClusterIP Service
storageIP:
  name: azure-storage
  type: ClusterIP
  port: 4001
  targetPort: 4001
  labels:
    app: mytube
    service: storage

# Storage ConfigMap
storageConfig:
  PORT: 4001
  STORAGE_ACCOUNT_NAME: "sentinel27"

#### DB SERVICE ######
# DB Deployment Object
db:
  replicaCount: 1

  image:
    repository: mhs20/mytube
    tag: mytube-db-010
    pullPolicy: IfNotPresent

  resources:
    limits:
      memory: "128Mi"
      cpu: "500m"

  service:
    name: mytube-db
    port: 4000

  labels:
    app: mytube
    environment: dev
    service: db

# Db ClusterIP Service
dbIP:
  name: mytube-db
  type: ClusterIP
  port: 4000
  targetPort: 27017
  labels:
    app: mytube
    service: db
