name: AWS Kubernetes Secrets 

on:
  repository_dispatch:
    types: [create_secrets]

jobs:
  create-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      ## Kubeconfig file to deploy on AWS cluster ##
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Fecth kubeconfig file
        run: |
          aws eks update-kubeconfig --name my-eks-cluster --kubeconfig ~/.kube/config

      - name: Create Dokcer Registry Secret
        run: |
          kubectl create secret docker-registry docker-registry-secret \
            --docker-username=${{ secrets.DOCKER_USERNAME }} \
            --docker-password=${{ secrets.DOCKER_PASSWORD }} \
            --docker-email=${{ secrets.DOCKER_EMAIL }} \
            --docker-server=https://index.docker.io/v1/

      - name: Create Azure Storage Secret
        run: |
            kubectl create secret generic azure-storage-access-key  \
            --from-literal=STORAGE_ACCESS_KEY=${{ secrets.AZURE_STORAGE_ACCESS_KEY}}
