name: Azure Kubernetes Secrets 

on:
  repository_dispatch:
    types: [create_secrets]

jobs:
  create-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: '1.27.0'  

      - name: Configure Kubeconfig
        run: |
          az aks get-credentials --resource-group aks-rg --name my-aks-cluster --file ~/.kube/config

      - name: Create Dokcer Registry Secret
        run: |
          kubectl create secret docker-registry docker-registry-secret \
            --docker-username=${{ secrets.DOCKER_USERNAME }} \
            --docker-password=${{ secrets.DOCKER_PASSWORD }} \
            --docker-email=${{ secrets.DOCKER_EMAIL }} \
            --docker-server=https://index.docker.io/v1/

      - name: Create Azure Storage Secret
        run: |
            kubectl create secret generic azure-storage-access-key  \
            --from-literal=STORAGE_ACCESS_KEY=${{ secrets.AZURE_STORAGE_ACCESS_KEY}}
