name: Build and Push Image for Streaming Service

on:
  push:
    paths:
      - 'MHS-20/MyProjects/microservices/my-tube/video-streaming'
  workflow_dispatch:

jobs:
  call-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Call reusable workflow
        uses: ./.github/workflows/build-and-push.yml
        with:
          image-dir: 'video-streaming'
