name: Build and Push Image for Azure Storage Service

on:
  push:
    paths:
      - 'MHS-20/MyProjects/microservices/my-tube/azure-storage'
  workflow_dispatch:

jobs:
  call-build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
    
      - name: Call reusable workflow
        uses: ./.github/workflows/docker-build-and-push.yml
        with:
          image-dir: 'azure-streaming'

      - name: Trigger next workflow with inputs
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{
            "event_type": "trigger_docker_build",
            "client_payload": {
              "image_dir": "azure-streaming"
            }
          }'
