name: Build and Push Image for Streaming Service

on:
  push:
    paths:
      - 'MHS-20/MyProjects/microservices/my-tube/video-streaming'
  workflow_dispatch:

permissions:
  contents: write
  actions: write    

jobs:
  call-build-and-push:
    runs-on: ubuntu-latest
    
    
    steps:
      - name: Trigger next workflow with inputs
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{
            "event_type": "trigger_docker_build",
            "client_payload": {
              "image_dir": "video-streaming", 
              "docker_repo": "mhs20/mytube-video-streaming"
            }
          }'
