name: Create clusters with terraform

on:
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
      - name: Run Terraform
        run: |
          cd ./microservices/my-tube
          terraform init
          terraform refresh
          terraform apply -auto-approve
