name: Create clusters with terraform

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_dir:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
      - name: Run Terraform
        run: |
          cd ./microservices/my-tube
          terraform init
          terraform refresh
          terraform apply -auto-approve

      - name: Call Service Deployment Workflow
        uses: ./.github/workflows/build-${{ inputs.image-dir }}-image.yml
        with:
          image_name: ${{ inputs.image-name }}
          image_dir: ${{ inputs.image-dir }}
