name: Create clusters with terraform

on:
  repository_dispatch:
    types: [trigger_clusters_creation]

permissions:
  contents: write  
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Run Terraform
        run: |
          cd ./microservices/my-tube
          terraform init
          terraform refresh
          terraform apply -auto-approve

      - name: Trigger next workflow with inputs
        run: |
          curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{
            "event_type": "trigger_deployment",
            "client_payload": {
              "image_name": "${{ github.event.client_payload.image_name }}",
              "image_dir": "${{ github.event.client_payload.image_dir }}"
            }
          }'
