name: Deploy Azure Storage to Clusters

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      ## Kubeconfig file to deploy on Azure cluster ##
      - name: Set up Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # create service principal

      - name: Fecth AKS kubeconfig file
        run: |
          az aks get-credentials --resource-group aks-rg --name my-aks-cluster --file $GITHUB_WORKSPACE/kubeconfig.yaml

      ## Set environment variable for kubeconfig ##
      - name: Set KUBECONFIG environment variable
        run: |
          echo "KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig.yaml" >> $GITHUB_ENV

      ## Deploy Specific Service with Terraform ##
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Run Terraform
        run: |
          cd ./microservices/my-tube/${{ github.event.client_payload.image_dir }}
          terraform init
          terraform refresh
          terraform apply -auto-approve -var=${{ github.event.client_payload.image_name }}
