name: Deploy to Kubernetes with Terraform

on:
  repository_dispatch:
    types: [deploy]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
      - name: Initialize Terraform
        run: terraform init
  
      - name: Refresh Terraform state
        run: terraform refresh
  
      - name: Apply Terraform configuration
        run: |
          terraform apply -auto-approve -var="image_name=${{ env.IMAGE_NAME }}"
