name: Deploy New Image to EKS

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_deployment]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      ## Kubeconfig file to deploy on AWS cluster ##
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Fecth EKS kubeconfig file
        run: |
          aws eks update-kubeconfig --name my-eks-cluster --kubeconfig ~/.kube/config

      ## Set environment variable for kubeconfig ##
      # - name: Set KUBECONFIG environment variable
      #   run: |
      #     echo "KUBECONFIG=$GITHUB_WORKSPACE/kubeconfig.yaml" >> $GITHUB_ENV

      ## Deploy Specific Service with Terraform ##
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Run Terraform
        run: |
          pwd
          ls -lr ./microservices/my-tube/
          cd ./microservices/my-tube/${{ github.event.client_payload.image_dir }}
          
          echo "image name: ${{ github.event.client_payload.image_name }}"
          cat ~/.kube/config
          
          terraform init
          terraform refresh
          terraform apply -auto-approve -var="image_name=${{ github.event.client_payload.image_name }}"
