name: Deploy Azure Storage to Clusters

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_dir:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

## Kubeconfig file to deploy on Azure cluster ## 
      - name: Set up Azure CLI
        uses: azure/setup-azure@v1
        with:
          azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Fecth AKS kubeconfig file
        run: | 
            az aks get-credentials --resource-group aks-rg --name my-aks-cluster --file kubeconfig.yaml

## Deploy Specific Service with Terraform ##
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
           cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
      - name: Run Terraform
        run: |
          cd ./microservices/my-tube/${{ inputs.image_dir }}
          terraform init
          terraform refresh
          terraform apply -auto-approve -var=${{ inputs.image_name }}
