name: Deploy Helm Chart to EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Setup kubectl
      run: |
        aws eks update-kubeconfig --name ${{ secrets.EKS_CLUSTER_NAME }} --region ${{ secrets.AWS_REGION }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Read image names
      id: read-images
      run: |
          streaming_image=$(cat streaming_image.txt)
          storage_image=$(cat storage_image.txt)
          echo "::set-output name=streaming_image::$streaming_image"
          echo "::set-output name=storage_image::$storage_image"

    - name: Deploy Helm Chart
      run: |
        helm upgrade --install testing ./charts/Chart.yaml \
          --set streaming.image.tag=${{ steps.read-images.outputs.streaming_image }} \
          --set storage.image.tag=${{ steps.read-images.outputs.strorage_image }} \
          --namespace default \
          --wait
