name: Deploy Helm Chart to EKS

on:
  workflow_dispatch:
  repository_dispatch:
    types: [trigger_deployment]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repo
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    - name: Setup kubectl
      run: |
        aws eks update-kubeconfig --name my-eks-cluster --region ${{ secrets.AWS_REGION }}

    - name: Install Helm
      run: |
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

    - name: Replace images tag in Helm values.yaml
      run: |

          ## Retrive latest tags
          STORAGE_TAG=$(curl -s "https://hub.docker.com/v2/repositories/mhs20/mytube-azure-storage/tags/?page_size=1" | jq -r '.results[0].name')
          STREAMING_TAG=$(curl -s "https://hub.docker.com/v2/repositories/mhs20/mytube-video-streaming/tags/?page_size=1" | jq -r '.results[0].name')
          DB_TAG=$(curl -s "https://hub.docker.com/v2/repositories/mhs20/mytube-db/tags/?page_size=1" | jq -r '.results[0].name')

          ## Substitue placeholder tags
          sed -i "s/STORAGE_TAG_PLACEHOLDER/$STORAGE_TAG/g" ./microservices/my-tube/chart/values.yaml
          sed -i "s/STREAMING_TAG_PLACEHOLDER/$STREAMING_TAG/g" ./microservices/my-tube/chart/values.yaml
          sed -i "s/DB_TAG_PLACEHOLDER/$DB_TAG/g" ./microservices/my-tube/chart/values.yaml

    - name: Deploy Helm Chart
      run: |
        pwd
        cd ./microservices/my-tube/chart
        helm upgrade --install testing .
